improve config file error management
before:
```
$ aerogramme companion reload
Error: No such file or directory (os error 2)
```
after:
```
$ aerogramme companion reload
Error: failed to read config file `aerogramme.toml`

Caused by:
No such file or directory (os error 2)
```
or if aerogramme.toml is invalid :
```
Error: failed to read config file `aerogramme.toml`

Caused by:
TOML parse error at line 1, column 1
|
1 |
| ^
missing field `imap`
```