add dedicated error for `hash_password`
before:
```
Enter password:
Error: Argon2 error: salt invalid: value to short
```

after:
```
Enter password:
Error: failed to hash password

Caused by:
0: salt invalid: value to short
1: value to short
```